/**
 * Single source of truth for identity, SEO defaults, and unfilled assets.
 *
 * Every fact here is verified — see CONTEXT-FOR-CLAUDE-CODE.md §6 (IDENTITY).
 * Nothing in this file may introduce a lines-of-code figure, a percentage
 * derived from one, or self-description language ("passionate", "hardworking").
 */

export const SITE = {
  name: 'Kavindu Ranathunga',
  legalName: 'R.A.K.N. Ranathunga',
  role: 'Full-stack Developer',
  location: 'Colombo, Sri Lanka',
  email: 'kavindu.rakn@gmail.com',
  github: 'https://github.com/kavindu-rakn',
  /** This site's own repository, used to link the footer's build stamp. */
  repo: 'https://github.com/kavindu-rakn/kavindu-rakn',
  education:
    'BSc (Hons) Information Technology, Software Engineering specialisation, SLIIT, 2022–2027',
  /** Site-level meta description. Kept under 160 characters for SERP display. */
  description:
    'Full-stack developer in Colombo, Sri Lanka. Largest contributor to TalentHub, a production platform at Sri Lanka Telecom Mobitel.',
  locale: 'en',
  /** Default Open Graph image. Does not exist yet — tracked in PLACEHOLDERS.ogDefault. */
  ogImage: '/og/default.png',
} as const;

/**
 * Assets and URLs that do not exist yet.
 *
 * BRIEF §5: "Placeholders for all of the above must be visually obvious in the
 * build so none of them can ship empty, exactly as the resume does with [PHONE]."
 *
 * Every entry here is rendered by <Placeholder /> with a high-visibility
 * treatment. `npm run lint:content` (added in Phase 3) fails the build if any
 * token still resolves to `null` at deploy time.
 */
export type PlaceholderSpec = {
  /** The literal token the brief specified, or a stable equivalent. */
  readonly token: string;
  /** Short human label shown in the rendered placeholder. */
  readonly label: string;
  /** What Kavindu has to do by hand to resolve it. */
  readonly action: string;
  /** Resolved value. `null` until supplied — never invent one. */
  readonly value: string | null;
};

export const PLACEHOLDERS = {
  schemashiftLive: {
    token: 'LIVE_URL_SCHEMASHIFT',
    label: 'SchemaShift live URL',
    action: 'Paste the Vercel deployment URL. Repo is private — do not link github.com.',
    value: 'https://schema-shift.vercel.app/',
  },
  tamarindLive: {
    token: 'LIVE_URL_TAMARIND',
    label: 'Hotel Tamarind Tree live URL',
    action: 'Paste the Vercel deployment URL. Repo is private — do not link github.com.',
    value: 'https://hotel-tamarind-tree.vercel.app/',
  },
  talenthubStack: {
    token: 'TALENTHUB_STACK',
    label: 'TalentHub technology stack',
    action:
      'CONTEXT §4 specifies a stack for every project except TalentHub. Confirm the real one — do not let it be guessed.',
    value: null,
  },
  linkedin: {
    token: 'LINKEDIN_URL',
    label: 'LinkedIn profile',
    action: 'Create the profile, then paste the URL. Do not invent one.',
    value: 'https://www.linkedin.com/in/kavindu-ranathunga/',
  },
  domain: {
    token: 'SITE_DOMAIN',
    label: 'Production domain',
    action:
      'Buy the domain and update `site` in astro.config.mjs. A vercel.app subdomain is an unforced signal.',
    value: 'https://kavindu-rakn.xyz',
  },
  screenshots: {
    token: 'SCREENSHOT_REQUIRED',
    label: 'Case-study imagery',
    action:
      'Two or three hero stills at 2x, plus one 10–20 second silent screen recording of the primary interaction.',
    value: null,
  },
  ogDefault: {
    token: 'OG_IMAGE_DEFAULT',
    label: 'Default Open Graph image',
    action: 'Produce /public/og/default.png at 1200×630, or a template that generates them.',
    // Generated by scripts/generate-og.mjs, which runs as part of `npm run build`.
    value: '/og/default.png',
  },
} as const satisfies Record<string, PlaceholderSpec>;

export type PlaceholderKey = keyof typeof PLACEHOLDERS;

/**
 * Deployment-status wording, shared by the grid card and the case study so the
 * two can never describe the same project differently.
 */
export const STATUS_LABEL = {
  'in-production': 'In production',
  'deployed-in-development': 'Deployed · in active development',
  live: 'Live',
} as const;

/** The literal tokens from the brief, mapped to the placeholder registry. */
export const LIVE_PLACEHOLDER_KEYS = {
  LIVE_URL_SCHEMASHIFT: 'schemashiftLive',
  LIVE_URL_TAMARIND: 'tamarindLive',
} as const;

/**
 * Navigation. Kept here so the header stays presentational.
 *
 * Work points at the grid on the index rather than a separate listing page —
 * a second page rendering the same six cards would be duplicate content for
 * no gain. Individual case studies live at /work/<slug>.
 */
export const NAV = [
  { href: '/', label: 'Index' },
  { href: '/#work', label: 'Work' },
  { href: '/about', label: 'About' },
] as const;
