/**
 * Single source of truth for identity, SEO defaults, and unfilled assets.
 *
 * Every fact here is verified against the resume and the repositories.
 * Nothing in this file may introduce a lines-of-code figure, a percentage
 * derived from one, or self-description language ("passionate", "hardworking").
 */

export const SITE = {
  name: 'Kavindu Ranathunga',
  legalName: 'R.A.K.N. Ranathunga',
  role: 'Product Engineer',
  location: 'Colombo, Sri Lanka',
  email: 'kavindu.rakn@gmail.com',
  github: 'https://github.com/kavindu-rakn',
  linkedin: 'https://www.linkedin.com/in/kavindu-ranathunga/',
  /** This site's own repository, used to link the footer's build stamp. */
  repo: 'https://github.com/kavindu-rakn/kavindu-rakn',
  education:
    'BSc (Hons) Information Technology, Software Engineering specialisation, SLIIT, 2022–2027',
  /** Site-level meta description. Kept under 160 characters for SERP display. */
  description:
    'Product engineer in Colombo, Sri Lanka. Core contributor to TalentHub, an enterprise production platform at Sri Lanka Telecom Mobitel.',
  locale: 'en-GB',
  /** Default Open Graph image. Generated into public/og/ by scripts/generate-og.mjs. */
  ogImage: '/og/default.png',
} as const;

/**
 * Assets and URLs that do not exist yet.
 *
 * An unfilled value must be visually obvious in the build so none can ship
 * empty, the way a resume does with [PHONE].
 *
 * `npm run lint:content --strict` fails the build if a token still resolves to
 * `null` at deploy time. Note that it can only catch tokens that actually reach
 * the HTML — a registry entry nothing renders is invisible to it.
 */
export type PlaceholderSpec = {
  /** The literal token the brief specified, or a stable equivalent. */
  readonly token: string;
  /** Short human label shown in the rendered placeholder. */
  readonly label: string;
  /** What Kavindu has to do by hand to resolve it. */
  readonly action: string;
  /** Resolved value. `null` until supplied — never invent one. */
  readonly value: string | null;
};

export const PLACEHOLDERS = {
  screenshots: {
    token: 'SCREENSHOT_REQUIRED',
    label: 'Case-study imagery',
    action:
      'Two or three hero stills at 2x, plus one 10–20 second silent screen recording of the primary interaction.',
    value: null,
  },
  ogDefault: {
    token: 'OG_IMAGE_DEFAULT',
    label: 'Default Open Graph image',
    action: 'Produce /public/og/default.png at 1200×630, or a template that generates them.',
    // Generated by scripts/generate-og.mjs, which runs as part of `npm run build`.
    value: '/og/default.png',
  },
} as const satisfies Record<string, PlaceholderSpec>;

export type PlaceholderKey = keyof typeof PLACEHOLDERS;

/**
 * Deployment-status wording, shared by the grid card and the case study so the
 * two can never describe the same project differently.
 */
export const STATUS_LABEL = {
  'in-production': 'In production',
  'deployed-in-development': 'Deployed · in active development',
  live: 'Live',
} as const;

/**
 * Navigation. Kept here so the header stays presentational.
 *
 * Work points at the grid on the index rather than a separate listing page —
 * a second page rendering the same six cards would be duplicate content for
 * no gain. Individual case studies live at /work/<slug>.
 */
export type NavItem = {
  readonly href: string;
  readonly label: string;
  /** A downloadable asset rather than a page. Never marked `aria-current`. */
  readonly file?: boolean;
};

export const NAV: readonly NavItem[] = [
  { href: '/#index', label: 'Index' },
  { href: '/#work', label: 'Work' },
  { href: '/about', label: 'About' },
  { href: '/#tech', label: 'Tech' },
  { href: '/#contact', label: 'Contact' },
  { href: '/kavindu-ranathunga-resume.pdf', label: 'Resume', file: true },
];

/**
 * The first commit.
 *
 * Every elapsed figure on the site is derived from this date. None of them is
 * written by hand, because a hand-written duration is correct only on the day it
 * is committed and silently wrong every day after.
 */
export const FIRST_COMMIT = '2025-08-17';

const NUMBER_WORDS = [
  'Zero', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight',
  'Nine', 'Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen',
  'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen', 'Twenty', 'Twenty-one',
  'Twenty-two', 'Twenty-three',
] as const;

/** Whole months between `from` and `to`, floored. */
export function monthsSince(from: string | Date = FIRST_COMMIT, to: Date = new Date()): number {
  const start = typeof from === 'string' ? new Date(`${from}T00:00:00Z`) : from;
  let months =
    (to.getUTCFullYear() - start.getUTCFullYear()) * 12 +
    (to.getUTCMonth() - start.getUTCMonth());
  if (to.getUTCDate() < start.getUTCDate()) months -= 1;
  return Math.max(0, months);
}

/**
 * "Twelve months", "Nineteen months", "Two years".
 *
 * Spelled out below twenty-four months because the phrase is used as a headline;
 * years after that, so the site never has to say "Thirty-seven months".
 * Sentence-cased: every use on the site starts a sentence or a heading.
 */
export function elapsedPhrase(from: string | Date = FIRST_COMMIT, to: Date = new Date()): string {
  const months = monthsSince(from, to);
  if (months < 24) {
    return `${NUMBER_WORDS[months] ?? months} month${months === 1 ? '' : 's'}`;
  }
  const years = Math.floor(months / 12);
  return `${NUMBER_WORDS[years] ?? years} years`;
}

/**
 * Positions, newest first.
 *
 * `period` is display text and is safe to hand-write: a date range in the past
 * never becomes wrong. `end` is the only perishable part, and it exists solely
 * so the About page can derive its own tense — `null` means current. Adding a
 * new role with `end: null` is what moves the page from "Most recently" back to
 * "Currently", with no prose to edit.
 */
export const ROLES = [
  {
    title: 'Full-stack Developer Intern',
    org: 'Sri Lanka Telecom Mobitel',
    period: 'February–August 2026',
    end: '2026-08-31' as string | null,
  },
] as const;

/** The role currently held, or `null` if between positions. */
export function currentRole(now: Date = new Date()) {
  return ROLES.find((r) => r.end === null || new Date(`${r.end}T23:59:59Z`) > now) ?? null;
}

/** The most recent role, current or not. */
export const LATEST_ROLE = ROLES[0];

/**
 * The one-paragraph version of /about, shown on the index card.
 *
 * Shared because the card used to restate these figures in its own words.
 */
export const ABOUT_PRECIS =
  'Core contributor to a platform in production that twenty developers built, rebuilding 27 of its 35 screens across 37 merged pull requests — alongside five projects of my own designed and shipped.';

/**
 * What he is open to. Stored as the object alone and composed into a sentence at
 * each use site, so the footer's "Open to" label and the About page's sentence
 * cannot drift apart.
 */
export const AVAILABILITY = 'Full - time and freelance work';

/**
 * Currently being learned, as opposed to shipped.
 *
 * This replaces the old "What I do not do" section, which listed technologies as
 * permanent exclusions and was factually wrong within a year of being written.
 * A list of what is being picked up ages in the right direction: entries move
 * out of it into a real project, they do not rot in place.
 */
export const LEARNING = ['React Native', 'Expo'] as const;
